[default]
extend-ignore-re = [
    "\\b[A-Z]{2,}\\b",
]

[default.extend-identifiers]
ratatui = "ratatui"

[default.extend-words]

[files]
extend-exclude = [
    "*.lock",
    "target/",
    ".git/",
    "*.svg",
]